server:
  port: 7000
  servlet:
    context-path: /login
spring:
  application:
    name: login-service
  config:
    import: configserver:http://localhost:8888
  zipkin:
    base-url: http://localhost:9411
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
olx.app.jwtSecret: olxSecretKey
olx.app.jwtExpirationMs: 86400000