server:
  port: 7000
  servlet:
    context-path: /login
spring:
  application:
    name: login-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: root
  jpa:
    hibernate:
     ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
olx.app.jwtSecret: olxSecretKey
olx.app.jwtExpirationMs: 86400000